version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - bookstore-api-db:/var/lib/postgresql/data

  bookstore-api:
    depends_on:
      - postgres
    build: ./bookstore-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_ROOT_PASSWORD
      DB_SCHEMA: $DB_DATABASE
      DB_PORT: $DB_DOCKER_PORT
    stdin_open: true
    tty: true
volumes: 
  bookstore-api-db:






